version: '3'
services:
  flask_test:
    build: .
    ports:
      - "8000:5000"
    env_file: docker/.env
    depends_on:
      - db
    command: ["bash", "docker/boot.sh"]
  db:
    image: postgres:12
    env_file: docker/.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    external: true