version: '3'
services:
  db:
    image: postgres:12
    env_file: docker/.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mq:
    image: 'bitnami/rabbitmq:latest'
    env_file: docker/.env
    ports:
      - "5673:5672"
      - '15673:15672'
  web:
    build: .
    env_file: docker/.env
    ports:
      - "8000:5000"
    depends_on:
      - db
  worker:
    build: .
    env_file: docker/.env
    depends_on:
      - beat
      - db
      - mq
    entrypoint: ["celery", "worker", "--app=flask_test_project.celery", "--pool=solo", "--loglevel=INFO"]
    volumes:
      - celerybeat:/app
  beat:
    build: .
    env_file: docker/.env
    depends_on:
      - mq
    entrypoint: [ "celery", "beat", "--app=flask_test_project.celery", "--loglevel=INFO" ]
    volumes:
      - celerybeat:/app
  flower:
    build: .
    env_file: docker/.env
    depends_on:
      - mq
    entrypoint: [ "celery", "flower", "--app=flask_test_project.celery", "--loglevel=INFO" ]
    volumes:
      - celerybeat:/app
    ports:
      - "8888:5555"
volumes:
  pgdata:
  celerybeat:
